// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1/advertisement.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Advertisement struct {
	StartTime *time.Time `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time,omitempty"`
	EndTime   *time.Time `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time,omitempty"`
	CreatedAt *time.Time `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at,omitempty"`
	UpdatedAt *time.Time `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at,omitempty"`
	Id        int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    int64      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Position  string     `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Content   string     `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Enable    bool       `protobuf:"varint,9,opt,name=enable,proto3" json:"enable,omitempty"`
	Remark    string     `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (m *Advertisement) Reset()         { *m = Advertisement{} }
func (m *Advertisement) String() string { return proto.CompactTextString(m) }
func (*Advertisement) ProtoMessage()    {}
func (*Advertisement) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{0}
}
func (m *Advertisement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Advertisement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Advertisement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Advertisement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Advertisement.Merge(m, src)
}
func (m *Advertisement) XXX_Size() int {
	return m.Size()
}
func (m *Advertisement) XXX_DiscardUnknown() {
	xxx_messageInfo_Advertisement.DiscardUnknown(m)
}

var xxx_messageInfo_Advertisement proto.InternalMessageInfo

func (m *Advertisement) GetStartTime() *time.Time {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Advertisement) GetEndTime() *time.Time {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *Advertisement) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Advertisement) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Advertisement) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Advertisement) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Advertisement) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Advertisement) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Advertisement) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *Advertisement) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type DeleteAdvertisementRequest struct {
	Id []int64 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (m *DeleteAdvertisementRequest) Reset()         { *m = DeleteAdvertisementRequest{} }
func (m *DeleteAdvertisementRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAdvertisementRequest) ProtoMessage()    {}
func (*DeleteAdvertisementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{1}
}
func (m *DeleteAdvertisementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteAdvertisementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteAdvertisementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteAdvertisementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAdvertisementRequest.Merge(m, src)
}
func (m *DeleteAdvertisementRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteAdvertisementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAdvertisementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAdvertisementRequest proto.InternalMessageInfo

func (m *DeleteAdvertisementRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetAdvertisementRequest struct {
	Position []string `protobuf:"bytes,1,rep,name=position,proto3" json:"position,omitempty"`
}

func (m *GetAdvertisementRequest) Reset()         { *m = GetAdvertisementRequest{} }
func (m *GetAdvertisementRequest) String() string { return proto.CompactTextString(m) }
func (*GetAdvertisementRequest) ProtoMessage()    {}
func (*GetAdvertisementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{2}
}
func (m *GetAdvertisementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAdvertisementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAdvertisementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAdvertisementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAdvertisementRequest.Merge(m, src)
}
func (m *GetAdvertisementRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetAdvertisementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAdvertisementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAdvertisementRequest proto.InternalMessageInfo

func (m *GetAdvertisementRequest) GetPosition() []string {
	if m != nil {
		return m.Position
	}
	return nil
}

type ListAdvertisementRequest struct {
	Page     int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size_    int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Wd       string   `protobuf:"bytes,3,opt,name=wd,proto3" json:"wd,omitempty"`
	Field    []string `protobuf:"bytes,4,rep,name=field,proto3" json:"field,omitempty"`
	Order    string   `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	Position []string `protobuf:"bytes,6,rep,name=position,proto3" json:"position,omitempty"`
	Enable   []bool   `protobuf:"varint,7,rep,packed,name=enable,proto3" json:"enable,omitempty"`
}

func (m *ListAdvertisementRequest) Reset()         { *m = ListAdvertisementRequest{} }
func (m *ListAdvertisementRequest) String() string { return proto.CompactTextString(m) }
func (*ListAdvertisementRequest) ProtoMessage()    {}
func (*ListAdvertisementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{3}
}
func (m *ListAdvertisementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListAdvertisementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListAdvertisementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListAdvertisementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAdvertisementRequest.Merge(m, src)
}
func (m *ListAdvertisementRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListAdvertisementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAdvertisementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAdvertisementRequest proto.InternalMessageInfo

func (m *ListAdvertisementRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAdvertisementRequest) GetSize_() int32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *ListAdvertisementRequest) GetWd() string {
	if m != nil {
		return m.Wd
	}
	return ""
}

func (m *ListAdvertisementRequest) GetField() []string {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *ListAdvertisementRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *ListAdvertisementRequest) GetPosition() []string {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *ListAdvertisementRequest) GetEnable() []bool {
	if m != nil {
		return m.Enable
	}
	return nil
}

type ListAdvertisementReply struct {
	Total         int64            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Advertisement []*Advertisement `protobuf:"bytes,2,rep,name=advertisement,proto3" json:"advertisement,omitempty"`
}

func (m *ListAdvertisementReply) Reset()         { *m = ListAdvertisementReply{} }
func (m *ListAdvertisementReply) String() string { return proto.CompactTextString(m) }
func (*ListAdvertisementReply) ProtoMessage()    {}
func (*ListAdvertisementReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{4}
}
func (m *ListAdvertisementReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListAdvertisementReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListAdvertisementReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListAdvertisementReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAdvertisementReply.Merge(m, src)
}
func (m *ListAdvertisementReply) XXX_Size() int {
	return m.Size()
}
func (m *ListAdvertisementReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAdvertisementReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListAdvertisementReply proto.InternalMessageInfo

func (m *ListAdvertisementReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListAdvertisementReply) GetAdvertisement() []*Advertisement {
	if m != nil {
		return m.Advertisement
	}
	return nil
}

type AdminDeleteAdvertisementRequest struct {
	Id []int64 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
}

func (m *AdminDeleteAdvertisementRequest) Reset()         { *m = AdminDeleteAdvertisementRequest{} }
func (m *AdminDeleteAdvertisementRequest) String() string { return proto.CompactTextString(m) }
func (*AdminDeleteAdvertisementRequest) ProtoMessage()    {}
func (*AdminDeleteAdvertisementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{5}
}
func (m *AdminDeleteAdvertisementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminDeleteAdvertisementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminDeleteAdvertisementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminDeleteAdvertisementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDeleteAdvertisementRequest.Merge(m, src)
}
func (m *AdminDeleteAdvertisementRequest) XXX_Size() int {
	return m.Size()
}
func (m *AdminDeleteAdvertisementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDeleteAdvertisementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDeleteAdvertisementRequest proto.InternalMessageInfo

func (m *AdminDeleteAdvertisementRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type AdminGetAdvertisementRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *AdminGetAdvertisementRequest) Reset()         { *m = AdminGetAdvertisementRequest{} }
func (m *AdminGetAdvertisementRequest) String() string { return proto.CompactTextString(m) }
func (*AdminGetAdvertisementRequest) ProtoMessage()    {}
func (*AdminGetAdvertisementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{6}
}
func (m *AdminGetAdvertisementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminGetAdvertisementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminGetAdvertisementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminGetAdvertisementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetAdvertisementRequest.Merge(m, src)
}
func (m *AdminGetAdvertisementRequest) XXX_Size() int {
	return m.Size()
}
func (m *AdminGetAdvertisementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetAdvertisementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetAdvertisementRequest proto.InternalMessageInfo

func (m *AdminGetAdvertisementRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AdminListAdvertisementRequest struct {
	Page  int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size_ int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Wd    string   `protobuf:"bytes,3,opt,name=wd,proto3" json:"wd,omitempty"`
	Field []string `protobuf:"bytes,4,rep,name=field,proto3" json:"field,omitempty"`
	Order string   `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
}

func (m *AdminListAdvertisementRequest) Reset()         { *m = AdminListAdvertisementRequest{} }
func (m *AdminListAdvertisementRequest) String() string { return proto.CompactTextString(m) }
func (*AdminListAdvertisementRequest) ProtoMessage()    {}
func (*AdminListAdvertisementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{7}
}
func (m *AdminListAdvertisementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminListAdvertisementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminListAdvertisementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminListAdvertisementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminListAdvertisementRequest.Merge(m, src)
}
func (m *AdminListAdvertisementRequest) XXX_Size() int {
	return m.Size()
}
func (m *AdminListAdvertisementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminListAdvertisementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminListAdvertisementRequest proto.InternalMessageInfo

func (m *AdminListAdvertisementRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *AdminListAdvertisementRequest) GetSize_() int32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *AdminListAdvertisementRequest) GetWd() string {
	if m != nil {
		return m.Wd
	}
	return ""
}

func (m *AdminListAdvertisementRequest) GetField() []string {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *AdminListAdvertisementRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type AdminListAdvertisementReply struct {
	Total         int64            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Advertisement []*Advertisement `protobuf:"bytes,2,rep,name=advertisement,proto3" json:"advertisement,omitempty"`
}

func (m *AdminListAdvertisementReply) Reset()         { *m = AdminListAdvertisementReply{} }
func (m *AdminListAdvertisementReply) String() string { return proto.CompactTextString(m) }
func (*AdminListAdvertisementReply) ProtoMessage()    {}
func (*AdminListAdvertisementReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf22cfb43e030be7, []int{8}
}
func (m *AdminListAdvertisementReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminListAdvertisementReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminListAdvertisementReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminListAdvertisementReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminListAdvertisementReply.Merge(m, src)
}
func (m *AdminListAdvertisementReply) XXX_Size() int {
	return m.Size()
}
func (m *AdminListAdvertisementReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminListAdvertisementReply.DiscardUnknown(m)
}

var xxx_messageInfo_AdminListAdvertisementReply proto.InternalMessageInfo

func (m *AdminListAdvertisementReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *AdminListAdvertisementReply) GetAdvertisement() []*Advertisement {
	if m != nil {
		return m.Advertisement
	}
	return nil
}

func init() {
	proto.RegisterType((*Advertisement)(nil), "api.v1.Advertisement")
	proto.RegisterType((*DeleteAdvertisementRequest)(nil), "api.v1.DeleteAdvertisementRequest")
	proto.RegisterType((*GetAdvertisementRequest)(nil), "api.v1.GetAdvertisementRequest")
	proto.RegisterType((*ListAdvertisementRequest)(nil), "api.v1.ListAdvertisementRequest")
	proto.RegisterType((*ListAdvertisementReply)(nil), "api.v1.ListAdvertisementReply")
	proto.RegisterType((*AdminDeleteAdvertisementRequest)(nil), "api.v1.AdminDeleteAdvertisementRequest")
	proto.RegisterType((*AdminGetAdvertisementRequest)(nil), "api.v1.AdminGetAdvertisementRequest")
	proto.RegisterType((*AdminListAdvertisementRequest)(nil), "api.v1.AdminListAdvertisementRequest")
	proto.RegisterType((*AdminListAdvertisementReply)(nil), "api.v1.AdminListAdvertisementReply")
}

func init() { proto.RegisterFile("api/v1/advertisement.proto", fileDescriptor_cf22cfb43e030be7) }

var fileDescriptor_cf22cfb43e030be7 = []byte{
	// 688 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xbf, 0x4e, 0xdc, 0x4c,
	0x10, 0xc7, 0xf7, 0xff, 0x06, 0xf1, 0x09, 0x96, 0x7f, 0x96, 0x01, 0x9f, 0xe5, 0xea, 0x84, 0x3e,
	0xd9, 0x3a, 0x3e, 0xd1, 0x7c, 0x14, 0xe8, 0x48, 0xa2, 0x08, 0x29, 0x05, 0xb2, 0x92, 0x26, 0x0d,
	0x32, 0xec, 0x70, 0x5a, 0x61, 0x7b, 0x1d, 0x7b, 0xef, 0x10, 0x29, 0x93, 0x17, 0x40, 0x4a, 0x9f,
	0x87, 0xc8, 0x23, 0xa4, 0x4a, 0x89, 0x94, 0x26, 0x5d, 0x22, 0xc8, 0x83, 0x44, 0x5e, 0xdb, 0xe1,
	0x0c, 0x76, 0x74, 0x29, 0xa2, 0x74, 0x3b, 0xe3, 0xf9, 0xfd, 0xd1, 0xcc, 0xec, 0x1a, 0x34, 0x37,
	0x64, 0xf6, 0x64, 0x60, 0xbb, 0x74, 0x82, 0x91, 0x60, 0x31, 0xfa, 0x18, 0x08, 0x2b, 0x8c, 0xb8,
	0xe0, 0xa4, 0xe5, 0x86, 0xcc, 0x9a, 0x0c, 0xb4, 0xde, 0x88, 0xf3, 0x91, 0x87, 0xb6, 0xcc, 0x9e,
	0x8c, 0xcf, 0x6c, 0xc1, 0x7c, 0x8c, 0x85, 0xeb, 0x87, 0x69, 0xa1, 0xb6, 0x32, 0xe2, 0x23, 0x2e,
	0x8f, 0x76, 0x72, 0xca, 0xb2, 0x9b, 0x19, 0x2c, 0x51, 0x70, 0x83, 0x80, 0x0b, 0x57, 0x30, 0x1e,
	0xc4, 0xd9, 0xd7, 0x8d, 0xfb, 0xa4, 0xe8, 0x87, 0xe2, 0x32, 0xfd, 0x68, 0xbe, 0xaf, 0xc3, 0xc2,
	0x70, 0xda, 0x11, 0xd9, 0x07, 0x88, 0x85, 0x1b, 0x89, 0xe3, 0x44, 0x5b, 0x6d, 0x18, 0x4a, 0x7f,
	0x7e, 0x47, 0xb3, 0x52, 0x0e, 0x2b, 0xe7, 0xb0, 0x9e, 0xe7, 0xc6, 0x0e, 0x1a, 0x57, 0x5f, 0x7b,
	0x8a, 0xd3, 0x95, 0x98, 0x24, 0x4b, 0xf6, 0xa0, 0x83, 0x01, 0x4d, 0xe1, 0xcd, 0x19, 0xe1, 0x6d,
	0x0c, 0xa8, 0x04, 0xef, 0x03, 0x9c, 0x46, 0xe8, 0x0a, 0xa4, 0xc7, 0xae, 0x50, 0x5b, 0xb3, 0xaa,
	0x67, 0x98, 0xa1, 0xb4, 0x3f, 0x0e, 0x69, 0x4e, 0xd0, 0x9e, 0x95, 0x20, 0xc3, 0x0c, 0x05, 0xf9,
	0x07, 0x6a, 0x8c, 0xaa, 0x8a, 0xa1, 0xf4, 0xeb, 0x4e, 0x8d, 0x51, 0xb2, 0x0e, 0xed, 0x71, 0x8c,
	0xd1, 0x31, 0xa3, 0x6a, 0x4d, 0x26, 0x5b, 0x49, 0x78, 0x48, 0x89, 0x06, 0x9d, 0x90, 0xc7, 0x2c,
	0x69, 0xb5, 0x5a, 0x37, 0x94, 0x7e, 0xd7, 0xf9, 0x19, 0x13, 0x15, 0xda, 0xa7, 0x3c, 0x10, 0x18,
	0x08, 0xb5, 0x23, 0x3f, 0xe5, 0x21, 0x59, 0x83, 0x16, 0x06, 0xee, 0x89, 0x87, 0x6a, 0xd7, 0x50,
	0xfa, 0x1d, 0x27, 0x8b, 0x92, 0x7c, 0x84, 0xbe, 0x1b, 0x9d, 0xab, 0x20, 0x01, 0x59, 0x64, 0xfe,
	0x0b, 0xda, 0x63, 0xf4, 0x50, 0x60, 0x61, 0x4a, 0x0e, 0xbe, 0x1a, 0x63, 0x7c, 0x67, 0xb6, 0x9e,
	0x9a, 0x35, 0x77, 0x61, 0xfd, 0x29, 0x8a, 0xd2, 0xd2, 0x69, 0xbb, 0x09, 0x60, 0xca, 0xae, 0xf9,
	0x41, 0x01, 0xf5, 0x19, 0x8b, 0xcb, 0x81, 0x04, 0x1a, 0xa1, 0x3b, 0x42, 0xd9, 0x92, 0xa6, 0x23,
	0xcf, 0x49, 0x2e, 0x66, 0xaf, 0x51, 0x76, 0xa4, 0xe9, 0xc8, 0x73, 0xe2, 0xe5, 0x82, 0x66, 0x9d,
	0xa8, 0x5d, 0x50, 0xb2, 0x02, 0xcd, 0x33, 0x86, 0x1e, 0x55, 0x1b, 0x52, 0x2d, 0x0d, 0x92, 0x2c,
	0x8f, 0x28, 0x46, 0x72, 0x35, 0xba, 0x4e, 0x1a, 0x14, 0xcc, 0xb5, 0x8a, 0xe6, 0xa6, 0x3a, 0xd6,
	0x36, 0xea, 0x77, 0x1d, 0x33, 0xcf, 0x61, 0xad, 0xc4, 0x73, 0xe8, 0x5d, 0x26, 0x1a, 0x82, 0x0b,
	0xd7, 0xcb, 0xa6, 0x98, 0x06, 0x64, 0x0f, 0x16, 0x0a, 0x77, 0x4f, 0xad, 0x19, 0xf5, 0xfe, 0xfc,
	0xce, 0xaa, 0x95, 0x5e, 0x3e, 0xab, 0x48, 0x54, 0xac, 0x35, 0x07, 0xd0, 0x1b, 0x52, 0x9f, 0x05,
	0xbf, 0x31, 0x0b, 0x0b, 0x36, 0x25, 0xa4, 0x6a, 0x20, 0xf7, 0x16, 0xcd, 0x7c, 0xab, 0xc0, 0x96,
	0x04, 0xfc, 0xcd, 0x49, 0x98, 0x21, 0x6c, 0x54, 0x99, 0xf8, 0x33, 0xad, 0xdd, 0xf9, 0xd8, 0x80,
	0xc5, 0x42, 0xc1, 0xf0, 0xe8, 0x90, 0x20, 0x2c, 0x3f, 0x92, 0x77, 0xba, 0xf8, 0x38, 0x95, 0x33,
	0x6a, 0xe5, 0x69, 0xd3, 0x78, 0xf3, 0xf9, 0xfb, 0xbb, 0x9a, 0x66, 0xae, 0xda, 0x65, 0x6f, 0xef,
	0xff, 0xca, 0x36, 0x39, 0x83, 0xe5, 0x17, 0xf2, 0xe6, 0xcf, 0x24, 0xb3, 0xf6, 0xe0, 0x1d, 0x79,
	0x92, 0x3c, 0xa5, 0xb9, 0x8e, 0x56, 0xad, 0x13, 0xc2, 0x72, 0xc9, 0xe6, 0x10, 0x33, 0xd7, 0xa9,
	0x5e, 0xab, 0x4a, 0xd1, 0x2d, 0x29, 0xba, 0xbe, 0x5d, 0x2e, 0x4a, 0x22, 0x58, 0xbc, 0xbf, 0x78,
	0xa4, 0x97, 0xcb, 0x55, 0xac, 0xa4, 0xa6, 0xe7, 0x05, 0xe5, 0xd3, 0xcf, 0x35, 0x49, 0x85, 0xe6,
	0x25, 0x2c, 0x3d, 0x00, 0x12, 0xe3, 0x17, 0x9c, 0xb3, 0xa9, 0x9a, 0x52, 0x75, 0x93, 0x68, 0xa5,
	0xaa, 0xb6, 0xc7, 0x62, 0x71, 0xb0, 0xfb, 0xe9, 0x46, 0x57, 0xae, 0x6f, 0x74, 0xe5, 0xdb, 0x8d,
	0xae, 0x5c, 0xdd, 0xea, 0x73, 0xd7, 0xb7, 0xfa, 0xdc, 0x97, 0x5b, 0x7d, 0x0e, 0xb2, 0x7f, 0xeb,
	0x91, 0xf2, 0x72, 0xc9, 0xe7, 0x11, 0x52, 0x7e, 0x9a, 0xd1, 0xec, 0x4d, 0x06, 0x27, 0x2d, 0xd9,
	0xd4, 0xff, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x85, 0xe1, 0xf7, 0x9d, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdvertisementAPIClient is the client API for AdvertisementAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdvertisementAPIClient interface {
	CreateAdvertisement(ctx context.Context, in *Advertisement, opts ...grpc.CallOption) (*Advertisement, error)
	UpdateAdvertisement(ctx context.Context, in *Advertisement, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAdvertisement(ctx context.Context, in *DeleteAdvertisementRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAdvertisement(ctx context.Context, in *GetAdvertisementRequest, opts ...grpc.CallOption) (*ListAdvertisementReply, error)
	ListAdvertisement(ctx context.Context, in *ListAdvertisementRequest, opts ...grpc.CallOption) (*ListAdvertisementReply, error)
}

type advertisementAPIClient struct {
	cc *grpc.ClientConn
}

func NewAdvertisementAPIClient(cc *grpc.ClientConn) AdvertisementAPIClient {
	return &advertisementAPIClient{cc}
}

func (c *advertisementAPIClient) CreateAdvertisement(ctx context.Context, in *Advertisement, opts ...grpc.CallOption) (*Advertisement, error) {
	out := new(Advertisement)
	err := c.cc.Invoke(ctx, "/api.v1.AdvertisementAPI/CreateAdvertisement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementAPIClient) UpdateAdvertisement(ctx context.Context, in *Advertisement, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/api.v1.AdvertisementAPI/UpdateAdvertisement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementAPIClient) DeleteAdvertisement(ctx context.Context, in *DeleteAdvertisementRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/api.v1.AdvertisementAPI/DeleteAdvertisement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementAPIClient) GetAdvertisement(ctx context.Context, in *GetAdvertisementRequest, opts ...grpc.CallOption) (*ListAdvertisementReply, error) {
	out := new(ListAdvertisementReply)
	err := c.cc.Invoke(ctx, "/api.v1.AdvertisementAPI/GetAdvertisement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advertisementAPIClient) ListAdvertisement(ctx context.Context, in *ListAdvertisementRequest, opts ...grpc.CallOption) (*ListAdvertisementReply, error) {
	out := new(ListAdvertisementReply)
	err := c.cc.Invoke(ctx, "/api.v1.AdvertisementAPI/ListAdvertisement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdvertisementAPIServer is the server API for AdvertisementAPI service.
type AdvertisementAPIServer interface {
	CreateAdvertisement(context.Context, *Advertisement) (*Advertisement, error)
	UpdateAdvertisement(context.Context, *Advertisement) (*emptypb.Empty, error)
	DeleteAdvertisement(context.Context, *DeleteAdvertisementRequest) (*emptypb.Empty, error)
	GetAdvertisement(context.Context, *GetAdvertisementRequest) (*ListAdvertisementReply, error)
	ListAdvertisement(context.Context, *ListAdvertisementRequest) (*ListAdvertisementReply, error)
}

// UnimplementedAdvertisementAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAdvertisementAPIServer struct {
}

func (*UnimplementedAdvertisementAPIServer) CreateAdvertisement(ctx context.Context, req *Advertisement) (*Advertisement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdvertisement not implemented")
}
func (*UnimplementedAdvertisementAPIServer) UpdateAdvertisement(ctx context.Context, req *Advertisement) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdvertisement not implemented")
}
func (*UnimplementedAdvertisementAPIServer) DeleteAdvertisement(ctx context.Context, req *DeleteAdvertisementRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAdvertisement not implemented")
}
func (*UnimplementedAdvertisementAPIServer) GetAdvertisement(ctx context.Context, req *GetAdvertisementRequest) (*ListAdvertisementReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdvertisement not implemented")
}
func (*UnimplementedAdvertisementAPIServer) ListAdvertisement(ctx context.Context, req *ListAdvertisementRequest) (*ListAdvertisementReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdvertisement not implemented")
}

func RegisterAdvertisementAPIServer(s *grpc.Server, srv AdvertisementAPIServer) {
	s.RegisterService(&_AdvertisementAPI_serviceDesc, srv)
}

func _AdvertisementAPI_CreateAdvertisement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Advertisement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementAPIServer).CreateAdvertisement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AdvertisementAPI/CreateAdvertisement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementAPIServer).CreateAdvertisement(ctx, req.(*Advertisement))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementAPI_UpdateAdvertisement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Advertisement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementAPIServer).UpdateAdvertisement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AdvertisementAPI/UpdateAdvertisement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementAPIServer).UpdateAdvertisement(ctx, req.(*Advertisement))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementAPI_DeleteAdvertisement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdvertisementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementAPIServer).DeleteAdvertisement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AdvertisementAPI/DeleteAdvertisement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementAPIServer).DeleteAdvertisement(ctx, req.(*DeleteAdvertisementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementAPI_GetAdvertisement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdvertisementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementAPIServer).GetAdvertisement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AdvertisementAPI/GetAdvertisement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementAPIServer).GetAdvertisement(ctx, req.(*GetAdvertisementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvertisementAPI_ListAdvertisement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdvertisementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvertisementAPIServer).ListAdvertisement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AdvertisementAPI/ListAdvertisement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvertisementAPIServer).ListAdvertisement(ctx, req.(*ListAdvertisementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdvertisementAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.AdvertisementAPI",
	HandlerType: (*AdvertisementAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAdvertisement",
			Handler:    _AdvertisementAPI_CreateAdvertisement_Handler,
		},
		{
			MethodName: "UpdateAdvertisement",
			Handler:    _AdvertisementAPI_UpdateAdvertisement_Handler,
		},
		{
			MethodName: "DeleteAdvertisement",
			Handler:    _AdvertisementAPI_DeleteAdvertisement_Handler,
		},
		{
			MethodName: "GetAdvertisement",
			Handler:    _AdvertisementAPI_GetAdvertisement_Handler,
		},
		{
			MethodName: "ListAdvertisement",
			Handler:    _AdvertisementAPI_ListAdvertisement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/advertisement.proto",
}

func (m *Advertisement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Advertisement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Advertisement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Remark) > 0 {
		i -= len(m.Remark)
		copy(dAtA[i:], m.Remark)
		i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Remark)))
		i--
		dAtA[i] = 0x52
	}
	if m.Enable {
		i--
		if m.Enable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0x42
	}
	if m.UpdatedAt != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.UpdatedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintAdvertisement(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x3a
	}
	if m.CreatedAt != nil {
		n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintAdvertisement(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x32
	}
	if m.EndTime != nil {
		n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.EndTime):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintAdvertisement(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x2a
	}
	if m.StartTime != nil {
		n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.StartTime):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintAdvertisement(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Position) > 0 {
		i -= len(m.Position)
		copy(dAtA[i:], m.Position)
		i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Position)))
		i--
		dAtA[i] = 0x1a
	}
	if m.UserId != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.UserId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DeleteAdvertisementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteAdvertisementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteAdvertisementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA6 := make([]byte, len(m.Id)*10)
		var j5 int
		for _, num1 := range m.Id {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		i -= j5
		copy(dAtA[i:], dAtA6[:j5])
		i = encodeVarintAdvertisement(dAtA, i, uint64(j5))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAdvertisementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAdvertisementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAdvertisementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Position) > 0 {
		for iNdEx := len(m.Position) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Position[iNdEx])
			copy(dAtA[i:], m.Position[iNdEx])
			i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Position[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ListAdvertisementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListAdvertisementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListAdvertisementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Enable) > 0 {
		for iNdEx := len(m.Enable) - 1; iNdEx >= 0; iNdEx-- {
			i--
			if m.Enable[iNdEx] {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
		}
		i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Enable)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Position) > 0 {
		for iNdEx := len(m.Position) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Position[iNdEx])
			copy(dAtA[i:], m.Position[iNdEx])
			i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Position[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Order) > 0 {
		i -= len(m.Order)
		copy(dAtA[i:], m.Order)
		i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Order)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Field) > 0 {
		for iNdEx := len(m.Field) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Field[iNdEx])
			copy(dAtA[i:], m.Field[iNdEx])
			i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Field[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Wd) > 0 {
		i -= len(m.Wd)
		copy(dAtA[i:], m.Wd)
		i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Wd)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Size_ != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ListAdvertisementReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListAdvertisementReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListAdvertisementReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Advertisement) > 0 {
		for iNdEx := len(m.Advertisement) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Advertisement[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAdvertisement(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Total != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AdminDeleteAdvertisementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminDeleteAdvertisementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminDeleteAdvertisementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA8 := make([]byte, len(m.Id)*10)
		var j7 int
		for _, num1 := range m.Id {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintAdvertisement(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AdminGetAdvertisementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminGetAdvertisementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminGetAdvertisementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AdminListAdvertisementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminListAdvertisementRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminListAdvertisementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Order) > 0 {
		i -= len(m.Order)
		copy(dAtA[i:], m.Order)
		i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Order)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Field) > 0 {
		for iNdEx := len(m.Field) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Field[iNdEx])
			copy(dAtA[i:], m.Field[iNdEx])
			i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Field[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Wd) > 0 {
		i -= len(m.Wd)
		copy(dAtA[i:], m.Wd)
		i = encodeVarintAdvertisement(dAtA, i, uint64(len(m.Wd)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Size_ != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x10
	}
	if m.Page != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AdminListAdvertisementReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminListAdvertisementReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AdminListAdvertisementReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Advertisement) > 0 {
		for iNdEx := len(m.Advertisement) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Advertisement[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAdvertisement(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Total != 0 {
		i = encodeVarintAdvertisement(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAdvertisement(dAtA []byte, offset int, v uint64) int {
	offset -= sovAdvertisement(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Advertisement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovAdvertisement(uint64(m.Id))
	}
	if m.UserId != 0 {
		n += 1 + sovAdvertisement(uint64(m.UserId))
	}
	l = len(m.Position)
	if l > 0 {
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	if m.StartTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.StartTime)
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	if m.EndTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.EndTime)
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	if m.CreatedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt)
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	if m.UpdatedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.UpdatedAt)
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	if m.Enable {
		n += 2
	}
	l = len(m.Remark)
	if l > 0 {
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	return n
}

func (m *DeleteAdvertisementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Id) > 0 {
		l = 0
		for _, e := range m.Id {
			l += sovAdvertisement(uint64(e))
		}
		n += 1 + sovAdvertisement(uint64(l)) + l
	}
	return n
}

func (m *GetAdvertisementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Position) > 0 {
		for _, s := range m.Position {
			l = len(s)
			n += 1 + l + sovAdvertisement(uint64(l))
		}
	}
	return n
}

func (m *ListAdvertisementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovAdvertisement(uint64(m.Page))
	}
	if m.Size_ != 0 {
		n += 1 + sovAdvertisement(uint64(m.Size_))
	}
	l = len(m.Wd)
	if l > 0 {
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	if len(m.Field) > 0 {
		for _, s := range m.Field {
			l = len(s)
			n += 1 + l + sovAdvertisement(uint64(l))
		}
	}
	l = len(m.Order)
	if l > 0 {
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	if len(m.Position) > 0 {
		for _, s := range m.Position {
			l = len(s)
			n += 1 + l + sovAdvertisement(uint64(l))
		}
	}
	if len(m.Enable) > 0 {
		n += 1 + sovAdvertisement(uint64(len(m.Enable))) + len(m.Enable)*1
	}
	return n
}

func (m *ListAdvertisementReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovAdvertisement(uint64(m.Total))
	}
	if len(m.Advertisement) > 0 {
		for _, e := range m.Advertisement {
			l = e.Size()
			n += 1 + l + sovAdvertisement(uint64(l))
		}
	}
	return n
}

func (m *AdminDeleteAdvertisementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Id) > 0 {
		l = 0
		for _, e := range m.Id {
			l += sovAdvertisement(uint64(e))
		}
		n += 1 + sovAdvertisement(uint64(l)) + l
	}
	return n
}

func (m *AdminGetAdvertisementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovAdvertisement(uint64(m.Id))
	}
	return n
}

func (m *AdminListAdvertisementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovAdvertisement(uint64(m.Page))
	}
	if m.Size_ != 0 {
		n += 1 + sovAdvertisement(uint64(m.Size_))
	}
	l = len(m.Wd)
	if l > 0 {
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	if len(m.Field) > 0 {
		for _, s := range m.Field {
			l = len(s)
			n += 1 + l + sovAdvertisement(uint64(l))
		}
	}
	l = len(m.Order)
	if l > 0 {
		n += 1 + l + sovAdvertisement(uint64(l))
	}
	return n
}

func (m *AdminListAdvertisementReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovAdvertisement(uint64(m.Total))
	}
	if len(m.Advertisement) > 0 {
		for _, e := range m.Advertisement {
			l = e.Size()
			n += 1 + l + sovAdvertisement(uint64(l))
		}
	}
	return n
}

func sovAdvertisement(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAdvertisement(x uint64) (n int) {
	return sovAdvertisement(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Advertisement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Advertisement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Advertisement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Position = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StartTime == nil {
				m.StartTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndTime == nil {
				m.EndTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enable = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remark", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Remark = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteAdvertisementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteAdvertisementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteAdvertisementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAdvertisement
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Id = append(m.Id, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAdvertisement
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthAdvertisement
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthAdvertisement
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Id) == 0 {
					m.Id = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAdvertisement
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Id = append(m.Id, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAdvertisementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAdvertisementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAdvertisementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Position = append(m.Position, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListAdvertisementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListAdvertisementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListAdvertisementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Field = append(m.Field, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Order = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Position = append(m.Position, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType == 0 {
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAdvertisement
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Enable = append(m.Enable, bool(v != 0))
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAdvertisement
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthAdvertisement
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthAdvertisement
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen
				if elementCount != 0 && len(m.Enable) == 0 {
					m.Enable = make([]bool, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAdvertisement
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Enable = append(m.Enable, bool(v != 0))
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Enable", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListAdvertisementReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListAdvertisementReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListAdvertisementReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Advertisement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Advertisement = append(m.Advertisement, &Advertisement{})
			if err := m.Advertisement[len(m.Advertisement)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminDeleteAdvertisementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminDeleteAdvertisementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminDeleteAdvertisementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAdvertisement
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Id = append(m.Id, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAdvertisement
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthAdvertisement
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthAdvertisement
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Id) == 0 {
					m.Id = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAdvertisement
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Id = append(m.Id, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminGetAdvertisementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminGetAdvertisementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminGetAdvertisementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminListAdvertisementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminListAdvertisementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminListAdvertisementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Wd = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Field = append(m.Field, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Order = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminListAdvertisementReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminListAdvertisementReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminListAdvertisementReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Advertisement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdvertisement
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Advertisement = append(m.Advertisement, &Advertisement{})
			if err := m.Advertisement[len(m.Advertisement)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAdvertisement(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAdvertisement
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAdvertisement(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAdvertisement
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAdvertisement
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAdvertisement
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAdvertisement
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAdvertisement
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAdvertisement        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAdvertisement          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAdvertisement = fmt.Errorf("proto: unexpected end of group")
)
